# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
